cloudflare:
    api_token: ENC[AES256_GCM,data:4bdvpwi4NmytIKgt5Pke8WvaMLUps1FKRq9yGQqy61mhP5quKypzCw==,iv:jk26iD9r8/87WTGnWL4uo3oZmB+B41hPm2uyA3+M/3Y=,tag:POmKRRd7+BhoCmRsP2Secw==,type:str]
    email: ENC[AES256_GCM,data:6XjU9FiQDfTKcuPANIiE+kryHUa2BA==,iv:sxW9coKJucBxhNCYken4CI9nsMz8+h0MFcbcs0RVTfU=,tag:Dp9LFHZN6nvh1hEXac/JNA==,type:str]
docker:
    username: ENC[AES256_GCM,data:2OyZaKkqXKVApg==,iv:igm1i6ZPIjhyGaeR4JGUkVsTOofEiJPmZrFEtAK1h6g=,tag:EuLFHoY8Z6j0vSUhbkym7A==,type:str]
    password: ENC[AES256_GCM,data:yDSVCPt9ATeOXThXCbGxy2k72KjUc8EkqnALvv55o7gDDjUy,iv:IJYrHDpdef6/DS0nWRz2CZVB4MDIpZrgcMo7xZ1Ogs4=,tag:2KxE+wvce0k1ihg3RDveJA==,type:str]
pihole:
    web_password: ENC[AES256_GCM,data:651XKi5CFtqaJ7JwqSN7yXhNVTXNj4jB/oybF98gObTudIuH35o2Ws5BD1U=,iv:kXhmwvnFPAYjoX8DVbNHMU8kQTXEVs6qObWDCvl4A2Y=,tag:z/mZQc0fbP6rpyzcWHB7tw==,type:str]
    ip_address: ENC[AES256_GCM,data:4i93RpYGXpJxMunW,iv:9PSNqaaI4dEK2bIZSLuRMNqFCRKbbforU14FzR84704=,tag:cEgMbkPYNnsxJ8EOzvdh7w==,type:str]
harbor:
    hostname: ENC[AES256_GCM,data:Ek5ZTKlwM5n3HUonMF9q,iv:l051nPWlEZ/fyZgzdRftUKQ4CJxK7LHwmLn6Oql+RZU=,tag:4nRS012osrGurwqZC2IKMg==,type:str]
    robot_username: ENC[AES256_GCM,data:iHTUjyFL9PgS,iv:XQI57xuzLodTBdo4QjMv4JQ5BcfQUBde0hOo0rzJ4rw=,tag:ivUJCMLF+Sg2+8V728r2pQ==,type:str]
    robot_token: ENC[AES256_GCM,data:obB2HrqabQ3kXBjUXwyjAEsb8wa7xVtQPG5vZ1eqT+0=,iv:e0ZXqcfshr366x5g0chdSySlWA/WLz/2pfhdGXq5/V0=,tag:02F8AurYZlGzoqLQr/8pWA==,type:str]
minio:
    root_user: ENC[AES256_GCM,data:KWE/coFtNsC8hw==,iv:kVoToATq18dHg9140L7DWkbuQUP5raML7MoUC8nUGD4=,tag:EAUp2s6rafpQLnINg3sM4g==,type:str]
    root_password: ENC[AES256_GCM,data:ddFQIvMF+cf/w3N+Bg==,iv:DJnSXepoqzsqPHGcTy7hR3bEGEQa2Jq9vByXJt+rvaU=,tag:tTM6B5gw8WA07ys1J9A+Qw==,type:str]
sops:
    age:
        - recipient: age12xe6r5ge6sqpwj4genlmrejtmsfhk6y0674z7r7k8leyy4paupqq7f6swg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS1hZeWhhY08va3JTcFpF
            QlNOR2FiNzRGcFJ1K1lkRlFqZVR5Nk5WSXl3ClR2dk5SSjR2OTFXR1NZUno3NEQr
            Q25DODh3d0ZIMGltYnZ3SWlsb3FQaVEKLS0tIHZTM2VhWHFOUVgraS9objJKSGNU
            SHhiaTE4ek4wMjU0Y0tZUXJ3ZjJZREUKpJncRBSaf+v2hIx8kGF02/yMcMWJG4MV
            1R408Gd/clREaFAPxkV8f4CS93A0yXo8+wnYkmB5tC/MJxl3gUNYJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T13:03:33Z"
    mac: ENC[AES256_GCM,data:HxYzMzAENyRz6X1TJ0hEc390AMYxRRU4Jrq3Iv8GcPXX6pT0X02WUzUD8utm8g1CQj/RNZNQr58+b/3iBpuW5ic0X1vgRXX5rdF8x3M3t0fBtU1xOLK/o8riszqRF4DBGs+48ngTDisugg5Eqs3cVurCrNEVluQ20TMmfcCQPho=,iv:MyT0YUvaPr82wV43KOzWAehg3ID+ZfhulnKCkSPYzZM=,tag:jJ9yV3VJt+5sj3yJmcwZZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
