cloudflare:
    api_token: ENC[AES256_GCM,data:4bdvpwi4NmytIKgt5Pke8WvaMLUps1FKRq9yGQqy61mhP5quKypzCw==,iv:jk26iD9r8/87WTGnWL4uo3oZmB+B41hPm2uyA3+M/3Y=,tag:POmKRRd7+BhoCmRsP2Secw==,type:str]
    email: ENC[AES256_GCM,data:6XjU9FiQDfTKcuPANIiE+kryHUa2BA==,iv:sxW9coKJucBxhNCYken4CI9nsMz8+h0MFcbcs0RVTfU=,tag:Dp9LFHZN6nvh1hEXac/JNA==,type:str]
docker:
    username: ENC[AES256_GCM,data:2OyZaKkqXKVApg==,iv:igm1i6ZPIjhyGaeR4JGUkVsTOofEiJPmZrFEtAK1h6g=,tag:EuLFHoY8Z6j0vSUhbkym7A==,type:str]
    password: ENC[AES256_GCM,data:yDSVCPt9ATeOXThXCbGxy2k72KjUc8EkqnALvv55o7gDDjUy,iv:IJYrHDpdef6/DS0nWRz2CZVB4MDIpZrgcMo7xZ1Ogs4=,tag:2KxE+wvce0k1ihg3RDveJA==,type:str]
pihole:
    web_password: ENC[AES256_GCM,data:651XKi5CFtqaJ7JwqSN7yXhNVTXNj4jB/oybF98gObTudIuH35o2Ws5BD1U=,iv:kXhmwvnFPAYjoX8DVbNHMU8kQTXEVs6qObWDCvl4A2Y=,tag:z/mZQc0fbP6rpyzcWHB7tw==,type:str]
    ip_address: ENC[AES256_GCM,data:4i93RpYGXpJxMunW,iv:9PSNqaaI4dEK2bIZSLuRMNqFCRKbbforU14FzR84704=,tag:cEgMbkPYNnsxJ8EOzvdh7w==,type:str]
harbor:
    hostname: ENC[AES256_GCM,data:Ek5ZTKlwM5n3HUonMF9q,iv:l051nPWlEZ/fyZgzdRftUKQ4CJxK7LHwmLn6Oql+RZU=,tag:4nRS012osrGurwqZC2IKMg==,type:str]
    robot_username: ENC[AES256_GCM,data:iHTUjyFL9PgS,iv:XQI57xuzLodTBdo4QjMv4JQ5BcfQUBde0hOo0rzJ4rw=,tag:ivUJCMLF+Sg2+8V728r2pQ==,type:str]
    robot_token: ENC[AES256_GCM,data:IjIZ9dv+Zstl3AIXKH62kmkRnBCQ9ln5LxCibUpgx/s=,iv:XpJsIufJag1Y8K6pRs8ayWEN0U2E7tKbZGwFeXFIiY0=,tag:qvMJhpKKzNLvQ/lu2+kouQ==,type:str]
    admin_password: ENC[AES256_GCM,data:hqZf+T7YhsW0SRCnUuOd+fo7D4ID9pxF,iv:6iqh6yo8tsS7l/FC87V2O/OzMu9VvdR3WZPDGGjI+lM=,tag:5hUDNmhKEItGIIQ4fyMnPw==,type:str]
    db_password: ENC[AES256_GCM,data:UR68ynRKCDcvdXqX,iv:n4vekTEvihW4To9i22T8zZaXdLRufaGgxwi1KTc7SPk=,tag:WyYzcg3QqZF15YCCzVoNcA==,type:str]
minio:
    root_user: ENC[AES256_GCM,data:KWE/coFtNsC8hw==,iv:kVoToATq18dHg9140L7DWkbuQUP5raML7MoUC8nUGD4=,tag:EAUp2s6rafpQLnINg3sM4g==,type:str]
    root_password: ENC[AES256_GCM,data:ddFQIvMF+cf/w3N+Bg==,iv:DJnSXepoqzsqPHGcTy7hR3bEGEQa2Jq9vByXJt+rvaU=,tag:tTM6B5gw8WA07ys1J9A+Qw==,type:str]
sops:
    age:
        - recipient: age12xe6r5ge6sqpwj4genlmrejtmsfhk6y0674z7r7k8leyy4paupqq7f6swg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS1hZeWhhY08va3JTcFpF
            QlNOR2FiNzRGcFJ1K1lkRlFqZVR5Nk5WSXl3ClR2dk5SSjR2OTFXR1NZUno3NEQr
            Q25DODh3d0ZIMGltYnZ3SWlsb3FQaVEKLS0tIHZTM2VhWHFOUVgraS9objJKSGNU
            SHhiaTE4ek4wMjU0Y0tZUXJ3ZjJZREUKpJncRBSaf+v2hIx8kGF02/yMcMWJG4MV
            1R408Gd/clREaFAPxkV8f4CS93A0yXo8+wnYkmB5tC/MJxl3gUNYJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T19:27:58Z"
    mac: ENC[AES256_GCM,data:ggTVaiFw9/MpSjRGjC7CR5D/sTIF6qanSlgq4mN5NfJfjl7EzDmAHrS3nXnmlPhNbbAsTaunb9fB2alCzQ0AyniR8EM579WuyQzoEpSsQ8pdsd8eo701r6M3w8cZEj5289hO0eGumiRmCgc9t7GU15KiXgg2GXzW0pguAMHhbsk=,iv:g6Q9FLf8qOgtfki+5uho5maIA+LSGb5JZqZmx6xbIyk=,tag:I8hkhstE6BusMnC3rou6eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
