PROXMOX_VE_ENDPOINT: ENC[AES256_GCM,data:HDKUmeWCpn77pzuoP5CLWeVLsPPHbZNW,iv:GmwQLf8Tg1mzhjYQQBKJQPvgyefMNA6vRDN9BH0jAoE=,tag:oXAea3vBusMVyUwOrXhbaQ==,type:str]
PROXMOX_VE_API_TOKEN_ID: ENC[AES256_GCM,data:G+8CNvhx/qqFCStKw/RZPmwb,iv:WGpm4+jZZkU8B0uhKaEEtwR2O8CBmGmFpfVDy+ie1fk=,tag:BjwzW5M1JU3OPbRnVS2Jkg==,type:str]
PROXMOX_VE_API_TOKEN_SECRET: ENC[AES256_GCM,data:BCRQRUI2fys0aUbmIPywpoqO/3I=,iv:GywOrIPWr8+vA9wIyVCrsbgP/8X7vRpLddH0+7Iu+j8=,tag:kDDPx1Ywm6+g4d30X4nMGQ==,type:str]
PROXMOX_VE_SSH_USERNAME: ENC[AES256_GCM,data:dpbqRGfrKVNb,iv:BQG3p4Z60kharBW2ZsjNrSwmMfEDOQlwT9DpqYIVVPY=,tag:gBM4Pn4JwLw32gaUyGwK1Q==,type:str]
PROXMOX_VE_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:CxCSpY2FBMNFOoaKJxuqqeuaumld0sHGLzi2Vj+TFSMe3ZE0kypaM7PDP3QRdRKsu4KAE+5epZiXzcpOfH7uFXrlq9bSbCJu7r9DCj1kWmW5A4FpgyZEVSCSkEAaOc7ib0fWaTPT0MVHnlkseW0HDd7JkYWU/jBpczNpfu3ea+NMXfRJOsBKs3YuMgz45aJYDjZfaRpe0f6QxNQl1D2WhZe7339C6UrM0gcJRKv8BV7GgUhu8msMBrZqCRELZyt2fLK8rgqj+nxB4uYaRSmaTWZH5xsT3WoVibfBHQVYhewa064N/vzZSGMcELCfQnQ/Ei/8pgsduFhcgQ+v+AV8/c619nZ2piIjHZg3YVtNQPPA33q4lNThdg+pE0m2Ae1mYpDoR9LZzGNUE4ptb5vFysTD3KeTVQjjxYxrcrgP8LcqcBZI4uVacudMV8YAlBu4/WFWidKwj9oQqTXlRNnZ6VMQn/DZ0jrXnPotUATyMTx8CNUM8G4IIZOAix7dD5QU+N2uZQKK7Kwe7PjatTpKCTU0+4BfUL91Wn1I,iv:8/JWp5MVjkXKBWTQZk3WOyqxvINzzX09D3FZOYeMo0M=,tag:YS+IDIp3V2+lOLZmcusQpw==,type:str]
sops:
    age:
        - recipient: age12xe6r5ge6sqpwj4genlmrejtmsfhk6y0674z7r7k8leyy4paupqq7f6swg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbHFKTmdrcE1BUnk3SmFK
            R2tEMDBYcDBjWTRneU44V2QzYk03eWY0OFVZCmQ3cXFhRDlhSHdFWElkWUxYMlBz
            cUllU3o0QXprWUF6SC9XdmlDZkNyRkEKLS0tIHZqdEQveEdKOGRMYXFUeldlbUcz
            bEJGNXBheUtzUTVSTTdzK3lvTGM1cDAKFHl0akg3fl3CQNLn2WwHn4nejqZJsRXV
            s+HNTX2CXPyEiJxhZ59ZVUVoTmf13R10hRrSewCGrahGfx2cbeLEjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T08:04:50Z"
    mac: ENC[AES256_GCM,data:6JRKkdl4RbJnqji0R1J2zW5EEvNs6658J6eDtAoWzrwMWtq2ZVbA6F2FJ40fMBCsUz4lWUPar8Ve2V9aQzl5jHFK/vSkP4Z11oxPip9a3Wh48ICgCQkWNkXpFIpFWwmFlUmd99ZPWzlJOj2+jQVnzsqWQRUXA7H2r+3TrTv4XTI=,iv:ftSZ7vTXGbAdhCIkeDSoRW5+A8D8wynurE3BECMQxeo=,tag:kkMYlzfhavMgwKyQ14pAoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
