# config/group_vars/control_plane.yml
---
# K8s cluster-specific variables are defined here
pod_cidr: "192.168.0.0/16"

# We use the full version to avoid kubeadm issues
kubernetes_version: "1.33.0"

# Private registry related variables
harbor_hostname: "harbor.bevz.net"
harbor_robot_username: "k8s-puller"
# harbor_robot_token is passed via sops/extra-vars, this is correct

target_namespaces:
  - default
  - kube-system
