# config/roles/argocd_install/defaults/main.yml
---
# Version from argocd.yml
argocd_version: "v2.13.2"

# Namespace for installation
argocd_namespace: "argocd"

# Manifest URL (from argocd.yml)
argocd_install_url: "https://raw.githubusercontent.com/argoproj/argo-cd/dc43124058130db9a747d141d86d7c2f4aac7bf9/manifests/install.yaml"
