apiVersion: v1
kind: Pod
metadata:
  name: nginx-ro-rootfs 
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:  
    - name: cache-volume
      mountPath: /var/cache/nginx
    - name: runtive-volume
      mountPath: /var/run
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: runtive-volume
      emptyDir: {}

