---
pod_cidr: "192.168.0.0/16"
kubernetes_version: "{{ k8s_short_version | default('1.33') }}"
harbor_hostname: "harbor.bevz.net" # Установите Ваш Harbor FQDN
harbor_robot_username: "k8s-puller"
harbor_robot_token: "" # Обязательно передать через --extra-vars
target_namespaces:
  - default
  - kube-system
