# config/roles/k8s_cluster_manager/defaults/main.yml
---
# Remove if planning to override in group_vars.
# If keeping, use only as fallback.
pod_cidr: "192.168.0.0/16"

# Keep if k8s_short_version is passed from outside
kubernetes_version: "{{ k8s_short_version | default('1.33.0') }}"
# Note: Set default to full format vX.Y.Z to avoid errors.

# REQUIRED VARIABLES (must be defined in config/secrets/ansible/extra_vars.sops.yml):
# harbor.hostname, harbor.robot_username, harbor.robot_token
