# config/roles/proxmox_template_builder/defaults/main.yml
---
# ID и имя будущего шаблона
template_vmid: 9013
template_name: "debian-13-generic-template"

# URL образа (Debian 13 Daily)
template_image_url: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.qcow2"
template_image_filename: "debian-13-generic.qcow2"

# Настройки ресурсов
template_memory: 2048
template_cores: 2
template_bridge: "vmbr0"
template_storage: "DataPool" # Где хранить диск (local-lvm, ceph, etc)

# Флаг принудительной пересборки (если шаблон уже есть)
force_recreate: true
