# config/roles/ingress_nginx_install/defaults/main.yml
---
# Версия из ingress-nginx.yml
ingress_nginx_version: "v1.12.0"

# URL манифеста для baremetal (из ingress-nginx.yml)
# Используем URL, привязанный к конкретному коммиту, для стабильности
ingress_nginx_deploy_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/8ee4384271e081578bb8f08eccf2f3b5a78ada25/deploy/static/provider/baremetal/deploy.yaml"
