# config/roles/localstack_setup/tasks/main.yml
---
# /config/roles/localstack_setup/tasks/main.yml

- name: Wait for apt locks to be released
  ansible.builtin.shell:
    cmd: "while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do echo 'Waiting for dpkg lock...' && sleep 10; done; while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt lists lock...' && sleep 10; done;"
  args:
    executable: /bin/bash
  when: ansible_os_family == "Debian"
  changed_when: false
  register: wait_for_lock
  until: wait_for_lock.rc == 0
  retries: 18
  delay: 10
  become: yes

- name: Установить необходимые пакеты для Docker
  ansible.builtin.apt:
    name: ["ca-certificates", "curl", "gnupg"]
    state: present
    update_cache: yes
  become: yes

- name: Добавить GPG-ключ Docker
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    force: true
  become: yes

- name: Добавить репозиторий Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture if ansible_architecture == 'aarch64' else 'amd64' }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: yes

- name: Убедиться, что Docker и Docker Compose установлены
  ansible.builtin.apt:
    name: ["docker-ce", "docker-compose-plugin"]
    state: present
    update_cache: yes
  become: yes

- name: Убедиться, что директории для LocalStack существуют
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  become: yes
  loop:
    - "{{ localstack_root_dir }}"
    - "{{ localstack_data_dir }}"

- name: Скопировать docker-compose.yml для LocalStack
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ localstack_root_dir }}/docker-compose.yml"
    mode: "0644"
  become: yes
  register: compose_file

- name: Запустить LocalStack (Docker Compose)
  community.docker.docker_compose_v2:
    project_src: "{{ localstack_root_dir }}"
    state: present # 'present' = up
  become: yes
