# config/roles/cert_manager_install/defaults/main.yml
# /config/roles/cert_manager_install/defaults/main.yml
---
cert_manager_version: "v1.16.2"
cert_manager_namespace: "cert-manager"
letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"
