# config/roles/certbot_setup/defaults/main.yml
# /config/roles/certbot_setup/defaults/main.yml
---
# Путь к venv
certbot_venv_path: "/opt/certbot"
# Путь к файлу с учетными данными
certbot_credentials_path: "/etc/letsencrypt/dns-multi.ini"

# Email для Let's Encrypt
certbot_email: "aleksey.bevz@gmail.com"

# Список доменов для сертификатов (из Вашего скрипта)
certbot_domains_to_create:
  - name: "bevz-net-wildcard"
    domains:
      - "*.bevz.net"
      - "bevz.net"
  - name: "bevz-dev-wildcard"
    domains:
      - "*.bevz.dev"
      - "bevz.dev"
  - name: "s3-minio-bevz-net"
    domains:
      - "s3.minio.bevz.net"
