# config/roles/certbot_setup/defaults/main.yml
# /config/roles/certbot_setup/defaults/main.yml
---
# Path to venv
certbot_venv_path: "/opt/certbot"
# Path to credentials file
certbot_credentials_path: "/etc/letsencrypt/dns-multi.ini"

# Email for Let's Encrypt
certbot_email: "aleksey.bevz@gmail.com"

# List of domains for certificates (from your script)
certbot_domains_to_create:
  - name: "bevz-net-wildcard"
    domains:
      - "*.bevz.net"
      - "bevz.net"
  - name: "bevz-dev-wildcard"
    domains:
      - "*.bevz.dev"
      - "bevz.dev"
  - name: "s3-minio-bevz-net"
    domains:
      - "s3.minio.bevz.net"
