# config/roles/certbot_setup/defaults/main.yml
# /config/roles/certbot_setup/defaults/main.yml
---
# Path to venv
certbot_venv_path: "/opt/certbot"
# Path to credentials file
certbot_credentials_path: "/etc/letsencrypt/dns-multi.ini"

# REQUIRED VARIABLES (must be defined in config/secrets/ansible/extra_vars.sops.yml):
# certbot_email: "admin@example.com"
# certbot_domains_to_create:
#   - name: "domain-wildcard"
#     domains:
#       - "*.example.com"
#       - "example.com"
