# config/playbooks/configure_apparmor.yml
# /config/playbooks/configure_apparmor.yml
---
- name: Configure AppArmor Profiles
  hosts: all
  become: yes

  vars:
    # Defaults to 'present'. Override via -e "addon_state=absent"
    addon_state: "present"

  roles:
    - role: apparmor_configure
