---
# playbooks/configure_timezone.yml

- name: Configure system timezone on all nodes
  hosts: all # üëà –£–∫–∞–∂–∏, –Ω–∞ –∫–∞–∫–∏—Ö —Ö–æ—Å—Ç–∞—Ö (all, kube_nodes, –∏ —Ç.–¥.)
  become: yes
  roles:
    - set_timezone
