# config/playbooks/create_templates.yml
---
- name: Build Proxmox Cloud-Init Templates
  hosts: proxmox_nodes
  become: yes # Root on Proxmox required for qm commands
  gather_facts: no

  roles:
    - role: proxmox_template_builder
      vars:
        # Variables can be overridden here for different distributions
        template_vmid: 9013
        template_name: "debian-13-generic-template"
        force_recreate: false
