# /config/playbooks/install_istio.yml
---
- name: Install or Uninstall Istio Service Mesh
  hosts: all
  become: yes

  vars:
    # Variable to override version
    requested_version: ""
    # STATE VARIABLE
    addon_state: "present" # (Override via -e "addon_state=absent")

  roles:
    - role: istio_install
