# config/playbooks/install_metallb.yml
# /config/playbooks/install_metallb.yml
---
- name: Install or Uninstall MetalLB
  hosts: all
  become: yes

  vars:
    addon_state: "present"
    requested_version: ""
    # (You can override IP pool here or in group_vars)
    # metallb_ip_range: "<K8S-INGRESS-IP>-<K8S-IP-END>"

  roles:
    - role: metallb_install
