# /config/playbooks/install_ingress_nginx.yml
---
- name: Install or Uninstall NGINX Ingress Controller
  hosts: all
  become: yes

  vars:
    requested_version: ""
    # STATE VARIABLE
    addon_state: "present" # (Override via -e "addon_state=absent")

  roles:
    - role: ingress_nginx_install
