# config/playbooks/install_argocd.yml
---
- name: Install or Uninstall ArgoCD
  hosts: all # iac-wrapper will limit this to k8s_master
  become: yes

  vars:
    # --- START FIX ---
    # Defaults to install.
    # Can be overridden via command line:
    # -e "addon_state=absent"
    addon_state: "present"
    # --- END FIX ---

    # Variable to override version
    requested_version: ""

  roles:
    - role: argocd_install
