# config/playbooks/install_bom.yml
# /config/playbooks/install_bom.yml
---
- name: Install or Uninstall BOM Scanner
  hosts: all # iac-wrapper будет ограничивать это до k8s_master
  become: yes

  vars:
    requested_version: ""
    # STATE VARIABLE
    addon_state: "present" # (Override via -e "addon_state=absent")

  roles:
    - role: bom_install
