# config/playbooks/setup_minio.yml
---
# /config/playbooks/setup_minio.yml
- name: Setup MinIO Server
  hosts: minio_servers # (Group name from Tofu outputs.tf)
  become: yes

  vars:
    addon_state: "present"

  roles:
    # 1. Set timezone
    - role: set_timezone

    # 2. Install MinIO
    - role: minio_setup
