# config/playbooks/setup_nginx-proxy.yml
# /config/playbooks/setup_nginx-proxy.yml
---
- name: Setup Nginx Proxy
  hosts: nginx_proxies # (Имя группы из Tofu outputs.tf)
  become: yes

  vars:
    addon_state: "present"

  roles:
    # 1. Устанавливаем Certbot (роль из предыдущего шага)
    - role: certbot_setup

    # 2. Устанавливаем Nginx (роль, которую мы только что создали)
    - role: nginx_proxy_setup
