# config/playbooks/setup_nginx-proxy.yml
# /config/playbooks/setup_nginx-proxy.yml
---
- name: Setup Nginx Proxy
  hosts: nginx_proxies # (Group name from Tofu outputs.tf)
  become: yes

  vars:
    addon_state: "present"

  roles:
    # 1. Install Certbot (role from previous step)
    - role: certbot_setup

    # 2. Install Nginx (role we just created)
    - role: nginx_proxy_setup
