# config/playbooks/setup_vpn.yml
---
- name: Setup Personal VPN on Raspberry Pi
  hosts: vpn_gateways
  become: yes

  vars:
    # Variables from SOPS
    wg_public_ip: "{{ wireguard.public_ip }}"
    wg_ui_password_hash: "{{ wireguard.ui_password_hash }}"
    wg_port: "51820"
    ntp_service_name: "systemd-timesyncd"

  roles:
    - role: set_timezone
    - role: wireguard_setup # This role should install Docker and WoL
