---
- name: (Debug) Verify Ansible Connection to k8s-lab-01
  hosts: k8s_master:k8s_worker # (Группа из Вашего Tofu outputs.tf)
  become: true
  
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - name: Verify 'abevz' user and sudo (whoami)
      ansible.builtin.command: whoami
      register: whoami_output

    - name: Print whoami output
      ansible.builtin.debug:
        msg: "I am running as '{{ whoami_output.stdout }}' (via become:true)"
