MINIO_ROOT_USER: ENC[AES256_GCM,data:ko1WBIbewbRIxA==,iv:E0jQV1v8TqdxvbZZHuwNCzTEgIvwrOkGjTCqhtik5LM=,tag:ENcvUzp6+bGLHqRpHnVMSA==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:u13oED9AZDW28phOWg==,iv:iDPOJRL1+hLeG+MrTpY2+vykjAqWVvtjeZ6pafrTuZY=,tag:Ua7YhdrnGjkZaDSYJbZcAw==,type:str]
sops:
    age:
        - recipient: age12xe6r5ge6sqpwj4genlmrejtmsfhk6y0674z7r7k8leyy4paupqq7f6swg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TStZQTY2bXlSMUo2d25m
            VE1hYkw1SUNkK2liaGMxVUsyUlFxZW1EUjJFCi83c1BxenU2VE5XdTAzbGZEMTJG
            MU1XdmQ3UzByU1ZXWjhaN3NxeXZTa1kKLS0tIHhqNGNmWTY2NWt3c29PZncwVEJy
            QjVXbmpmZ1JDSWJTOEZrajU2R05hVm8KIxwQHF1tVHCDvG2M5nx3fiEYgt55hm5l
            ZuAgWulmqoBBs+XluFzGF2CXcwKPt4zIBTIdOhDcsLrHEbpbfCH1sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T06:01:12Z"
    mac: ENC[AES256_GCM,data:CC7p95u6412tE0Ckj7Y0lrA/a3vYv8odjsUuacRGV+kHcKOt19y2Zcz1XnHqpEfhaRQWQ5HMig68RK4O6PFofDtOtFCjbjJ6kYYmbPni61n+nkirh9mlOuTRZDL7/n2IYVBiGraNQ0XImNES6cPFCEIn68ySX0r78O2P1Y0tzFg=,iv:A39+ZSqDp5qlwTJf32njoxOYWL4b93euHKTX7nSlh1g=,tag:pXt9f4YTPXzUiR4QEA1wlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
